// NOVA Food Classification System indicators

// Group 4: Ultra-processed foods
export const ultraProcessedIndicators = [
  // Additives that make products ultra-processed
  "high fructose corn syrup",
  "hydrogenated",
  "hydrolyzed",
  "interesterified",
  "maltodextrin",
  "modified starch",
  "protein isolate",
  "soy protein isolate",
  "textured vegetable protein",
  "invert sugar",
  "corn syrup",
  "dextrose",
  "glucose syrup",
  "aspartame",
  "sucralose",
  "acesulfame",
  "saccharin",
  "stevia",
  "polydextrose",
  "carrageenan",
  "guar gum",
  "gellan gum",
  "mono and diglycerides",
  "sodium stearoyl lactylate",
  "soy lecithin",
  "calcium disodium EDTA",
  "BHA",
  "BHT",
  "TBHQ",
  "sodium nitrite",
  "sodium nitrate",
  "potassium nitrate",
  "sodium benzoate",
  "potassium sorbate",
  "calcium propionate",
  "phosphoric acid",
  "artificial flavor",
  "natural flavor",
  "artificial color",
  "red 40",
  "yellow 5",
  "yellow 6",
  "blue 1",
  "blue 2",
  "green 3",
  "red 3",
  "caramel color",
  "annatto",
  "titanium dioxide",
  "polysorbate",
  "propylene glycol",
  "xanthan gum",
  "cellulose",
  "microcrystalline cellulose",
  "methylcellulose",
  "carboxymethylcellulose",
  "dextrin",
  "maltodextrin",
  "datem",
  "monoglycerides",
  "diglycerides",
  "glycerin",
  "sorbitol",
  "mannitol",
  "xylitol",
  "erythritol",
  "maltitol",
  "isomalt",
  "lactitol",
  "sodium aluminum phosphate",
  "sodium acid pyrophosphate",
  "sodium aluminum sulfate",
  "calcium phosphate",
  "disodium phosphate",
  "trisodium phosphate",
  "sodium phosphate",
  "potassium phosphate",
  "calcium silicate",
  "silicon dioxide",
  "sodium silico aluminate",
  "sodium citrate",
  "potassium citrate",
  "calcium citrate",
  "citric acid",
  "lactic acid",
  "fumaric acid",
  "malic acid",
  "sodium lactate",
  "calcium lactate",
  "potassium lactate",
  "sodium diacetate",
  "sodium erythorbate",
  "sodium ascorbate",
  "tocopherols",
  "ascorbic acid",
  "ascorbyl palmitate",
  "sodium hexametaphosphate",
  "sodium tripolyphosphate",
  "sodium pyrophosphate",
  "disodium guanylate",
  "disodium inosinate",
  "monosodium glutamate",
  "autolyzed yeast extract",
  "hydrolyzed vegetable protein",
  "hydrolyzed soy protein",
  "hydrolyzed wheat protein",
  "hydrolyzed corn protein",
  "yeast extract",
  "soy sauce",
  "worcestershire sauce",
  "smoke flavor",
  "caramel",
  "annatto extract",
  "paprika extract",
  "turmeric extract",
  "beta carotene",
  "calcium carbonate",
  "calcium sulfate",
  "sodium bicarbonate",
  "ammonium bicarbonate",
  "potassium bicarbonate",
  "sodium carbonate",
  "potassium carbonate",
  "calcium hydroxide",
  "sodium hydroxide",
  "potassium hydroxide",
  "calcium oxide",
  "magnesium oxide",
  "aluminum sulfate",
  "ammonium sulfate",
  "calcium sulfate",
  "magnesium sulfate",
  "potassium sulfate",
  "sodium sulfate",
  "sodium sulfite",
  "sodium bisulfite",
  "potassium bisulfite",
  "sodium metabisulfite",
  "potassium metabisulfite",
  "sulfur dioxide",
  "calcium chloride",
  "magnesium chloride",
  "potassium chloride",
  "sodium chloride",
  "ammonium chloride",
  "calcium lactate",
  "calcium gluconate",
  "calcium glycerophosphate",
  "calcium phytate",
  "ferric orthophosphate",
  "ferrous fumarate",
  "ferrous gluconate",
  "ferrous sulfate",
  "magnesium phosphate",
  "magnesium carbonate",
  "manganese sulfate",
  "potassium iodide",
  "potassium iodate",
  "selenium dioxide",
  "sodium selenite",
  "sodium selenate",
  "chromium chloride",
  "chromium picolinate",
  "copper gluconate",
  "copper sulfate",
  "manganese chloride",
  "manganese citrate",
  "manganese gluconate",
  "molybdenum chloride",
  "sodium molybdate",
  "zinc chloride",
  "zinc gluconate",
  "zinc oxide",
  "zinc sulfate"
];

// Group 3: Processed foods
export const processedIndicators = [
  "sugar",
  "salt",
  "oil",
  "fat",
  "butter",
  "preservative",
  "vinegar",
  "cured",
  "smoked",
  "pickled",
  "salted",
  "canned",
  "bottled",
  "fermented",
  "cheese",
  "bread",
  "beer",
  "wine",
  "tofu"
];

// Group 2: Processed culinary ingredients
export const processedCulinaryIndicators = [
  "olive oil",
  "coconut oil",
  "avocado oil",
  "butter",
  "lard",
  "honey",
  "maple syrup",
  "vinegar",
  "salt",
  "spices",
  "herbs",
  "baking powder",
  "baking soda",
  "yeast",
  "corn starch",
  "arrowroot",
  "tapioca starch"
];